import { Link, useParams } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Bell, Check, ChevronRight, CircleDot, ShieldCheck } from "lucide-react";
import { AppWindow, EmptyState, GhostButton, Greeting, HeatButton, InkButton, InkWidget, PaperCard, ReceiptCard, Row, StatTile, StatusDot, Timeline, ToastStrip } from "@/components/byline";
import { agents, categories, receipts, studios } from "@/lib/byline-data";

export function WakePage() {
  return <AppWindow rightRail><div className="space-y-6"><ToastStrip>Ritual is offline. You are on Byline local mode. Receipts are simulated.</ToastStrip><Greeting title="Good morning, Maren." action={<HeatButton asChild><Link to="/studios">Hire</Link></HeatButton>}/><div className="grid gap-3 sm:grid-cols-3"><StatTile label="Network" value="LOCAL" note="Chain 1979" seal="R"/><StatTile label="Jobs today" value="4 JOBS" note="3 accepted" seal="J"/><StatTile label="Your desk" value="3 PACKS" note="0 in flight" seal="P"/></div><section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-2xl text-paper">This week</h2><span className="text-xs text-paper/50">4 quiet entries</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Recommended", "Try Reviewer-7", "12 receipts"],["Starved", "Vellum needs a wake", "2 wakes left"],["Pack", "Research credits", "31 of 50"],["A2A", "Nested source check", "1 job"]].map(([eyebrow,title,note], i)=><PaperCard key={title} className="min-h-40"><span className={i===1 ? "text-xs text-starve" : "text-xs text-ink/45"}>{eyebrow}</span><h3 className="mt-7 font-display text-xl leading-tight">{title}</h3><div className="mt-5 h-1 rounded-full bg-ink/10"><div className="h-full rounded-full bg-ink/45" style={{width:`${35+i*15}%`}}/></div><p className="mt-2 font-mono text-[10px] text-ink/45">{note}</p></PaperCard>)}</div></section><section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-2xl text-paper">Recent receipts</h2><Link to="/receipt/$id" params={{id:"R-1979"}} className="text-xs text-paper/60">Open latest</Link></div><div className="overflow-hidden rounded-[22px] bg-ink/18 ring-1 ring-paper/10">{receipts.slice(0,4).map(r=><ReceiptCard key={r.id} {...r}/>)}</div></section></div></AppWindow>;
}

export function StudiosPage() {
  return <AppWindow><div className="mx-auto max-w-5xl space-y-6"><ToastStrip>48 live bylines across research, operations, code, and agent-to-agent work.</ToastStrip><Greeting title="Studios" action={<InkButton>Following 5</InkButton>}/><p className="font-display text-5xl text-paper">48 <span className="text-2xl text-paper/55">live bylines</span></p><PaperCard className="p-0 overflow-hidden">{studios.map((studio, i)=><Link key={studio.handle} to="/s/$handle" params={{handle:studio.handle}} className="grid min-h-20 grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-ink/8 px-5 last:border-0 hover:bg-fog"><div className="min-w-0"><p className="font-medium">{studio.name}</p><p className={i===1?"mt-1 text-xs text-starve":"mt-1 text-xs text-ink/50"}>{studio.agents} agents · {studio.accepted}</p></div><span className="flex items-center gap-3 text-sm">Follow <ChevronRight className="size-4 text-ink/40"/></span></Link>)}</PaperCard></div></AppWindow>;
}

export function StudioPage() {
  const { handle } = useParams({ from: "/s/$handle" }); const studio = studios.find(s=>s.handle===handle) ?? studios[0]; if (!studio) return null; const ownAgents=agents.filter(a=>a.studio===studio.name);
  return <AppWindow><div className="mx-auto max-w-5xl space-y-6"><ToastStrip>Studio receipts are simulated while Ritual is offline.</ToastStrip><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><div className="flex min-w-0 items-center gap-4"><span className="tactile-seal grid size-16 shrink-0 place-items-center rounded-[46%_54%_55%_45%] font-display text-2xl text-paper">{studio.name[0]}</span><div className="min-w-0"><h1 className="truncate font-display text-4xl text-paper">{studio.name}</h1><p className="mt-1 font-mono text-xs text-paper/55"><StatusDot/> {studio.handle}.ritual · 0x71…8a2</p></div></div><InkButton>Follow</InkButton></div><PaperCard><div className="grid grid-cols-2 gap-6 sm:grid-cols-4">{[["Agents",studio.agents],["Accepted",studio.accepted.split(" ")[0]],["Receipts","128"],["Median","41s"]].map(([l,v])=><div key={l}><p className="text-xs text-ink/45">{l}</p><p className="mt-2 font-display text-3xl">{v}</p></div>)}</div></PaperCard><div className="flex gap-2"><GhostButton><Bell/> Ship</GhostButton><GhostButton>Break</GhostButton><GhostButton>Price</GhostButton><GhostButton>Starve</GhostButton></div><div className="grid gap-3 md:grid-cols-2">{ownAgents.length?ownAgents.map(a=><Link key={a.id} to="/a/$id" params={{id:a.id}}><PaperCard className="min-h-48"><div className="flex justify-between"><span className="text-xs text-ink/45">{a.category}</span><StatusDot status={a.status}/></div><h2 className="mt-10 font-display text-3xl">{a.name}</h2><p className="mt-2 text-sm text-ink/55">{a.description}</p><p className="mt-5 font-mono text-xs">{a.price}</p></PaperCard></Link>):<EmptyState message="No agents are published here yet." action="Follow studio"/>}</div></div></AppWindow>;
}

export function AgentPage() {
  const { id } = useParams({ from: "/a/$id" }); const agent=agents.find(a=>a.id===id) ?? agents[0]; const [offer,setOffer]=useState("try"); if (!agent) return null;
  return <AppWindow><div className="mx-auto max-w-6xl space-y-6"><ToastStrip>Receipts are simulated in local mode.</ToastStrip><Greeting title={agent.name} action={<InkButton asChild><Link to="/s/$handle" params={{handle:agent.studio.toLowerCase().replaceAll(" ","-")}}>View studio</Link></InkButton>}/><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-4"><PaperCard><p className="text-xs text-ink/45">{agent.studio} · {agent.category}</p><h2 className="mt-5 font-display text-3xl">Does</h2><p className="mt-2 text-sm leading-6 text-ink/60">{agent.description}</p><h2 className="mt-6 font-display text-2xl">Does not</h2><p className="mt-2 text-sm leading-6 text-ink/60">Move funds, publish without approval, or retain private context.</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-fog p-3">Read supplied files</div><div className="rounded-xl bg-fog p-3">Write scoped output</div></div></PaperCard><PaperCard className="p-0 overflow-hidden"><div className="px-5 py-4"><h2 className="font-display text-2xl">Last 20 receipts</h2></div>{receipts.slice(0,5).map(r=><Row key={r.id} title={r.status.toUpperCase()} meta={<span className="font-mono">{r.id} · SIMULATED</span>} trailing={<span className="font-mono text-xs">{r.amount}</span>}/>)}</PaperCard></div><InkWidget className="h-fit lg:sticky lg:top-7"><p className="text-xs uppercase tracking-[0.04em] text-paper/45">Try</p><p className="mt-3 font-display text-4xl">14 WAKES</p><p className="mt-1 font-mono text-[10px] text-paper/45">CREATOR-OPERATED</p><div className="mt-7 space-y-2">{[["try","Try","0.00 labor + 0.12 buffer"],["desk","Desk 7 days","4.00 RITUAL"],["pack","Pack 50","2.40 RITUAL"]].map(([value,label,price])=><button key={value} onClick={()=>setOffer(value ?? "try")} className={`grid w-full grid-cols-[1fr_auto] rounded-xl border p-3 text-left text-sm ${offer===value?"border-paper/40 bg-paper/10":"border-paper/10"}`}><span>{label}</span><span className="font-mono text-xs text-paper/55">{price}</span></button>)}</div><HeatButton className="mt-5 w-full" asChild><Link to="/j/$id" params={{id:"J-018"}}>Try</Link></HeatButton></InkWidget></div></div></AppWindow>;
}

export function JobPage() { const [decision,setDecision]=useState<"pending"|"accepted"|"rejected">("pending"); return <AppWindow><div className="mx-auto max-w-6xl space-y-6"><ToastStrip>Job J-018 is running locally. No chain write will occur.</ToastStrip><Greeting title="Reviewer-7 in session"/><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_400px]"><InkWidget><p className="mb-5 text-xs uppercase tracking-[0.04em] text-paper/45">Job timeline</p><Timeline current={decision==="pending"?5:8}/><div className="mt-6 rounded-xl bg-paper/5 p-3 font-mono text-[10px] text-paper/45">SIMULATED · 0x71a9…33e0 · TEE attest pending</div></InkWidget><PaperCard><p className="text-xs uppercase tracking-[0.04em] text-ink/45">Output preview</p><h2 className="mt-4 font-display text-3xl">Recommendation</h2><p className="mt-3 text-sm leading-6 text-ink/60">The evidence supports publishing with one qualification: distinguish measured acceptance from self-reported completion.</p><div className="mt-6 border-t border-ink/8 pt-5"><p className="text-sm font-medium">3 sources checked</p><p className="mt-1 font-mono text-[10px] text-ink/45">41s · 0.38 RITUAL · TEE</p></div>{decision==="pending"?<div className="mt-8 flex gap-2"><HeatButton onClick={()=>setDecision("accepted")}>Accept</HeatButton><GhostButton onClick={()=>setDecision("rejected")}>Reject</GhostButton></div>:<p className="mt-8 flex items-center gap-2 text-sm"><StatusDot status={decision==="accepted"?"live":"asleep"}/>{decision==="accepted"?"Accepted. Receipt ready.":"Rejected. No settlement."}</p>}</PaperCard></div><Link to="/receipt/$id" params={{id:"R-1979"}} className="inline-flex items-center gap-2 text-sm text-paper">View on Ritual <ArrowRight className="size-4"/></Link></div></AppWindow>}

export function ReceiptPage() { const { id }=useParams({from:"/receipt/$id"}); return <AppWindow><div className="mx-auto grid min-h-[75vh] max-w-4xl place-items-center"><PaperCard className="w-full p-8 md:p-14"><div className="flex items-center justify-between"><p className="font-mono text-xs text-ink/45">BYLINE RECEIPT · {id}</p><span className="font-mono text-[10px] text-ink/40">SIMULATED</span></div><p className="mt-20 font-display text-6xl leading-none md:text-8xl">ACCEPTED</p><div className="mt-12 grid gap-6 border-y border-ink/8 py-6 sm:grid-cols-4"><div><p className="text-xs text-ink/45">Agent</p><p className="mt-1">Reviewer-7</p></div><div><p className="text-xs text-ink/45">Cost</p><p className="mt-1">0.38 RITUAL</p></div><div><p className="text-xs text-ink/45">Time</p><p className="mt-1">41s</p></div><div><p className="text-xs text-ink/45">Compute</p><p className="mt-1">TEE</p></div></div><p className="mt-6 font-mono text-xs text-ink/45">maya.eth · 0x71a9…33e0</p><div className="mt-12 flex items-center justify-between"><p className="flex items-center gap-2 text-sm"><StatusDot/> Settled on Ritual</p><HeatButton asChild><Link to="/a/$id" params={{id:"1"}}>Try this agent</Link></HeatButton></div></PaperCard></div></AppWindow> }

export function LaddersPage() { const { class: className }=useParams({from:"/ladders/$class"}); return <AppWindow><div className="mx-auto max-w-5xl space-y-6"><ToastStrip>Ranked on delivered work. Tokens are not a score.</ToastStrip><Greeting title={`${className[0]?.toUpperCase()}${className.slice(1)} ladder`}/><div className="flex flex-wrap gap-2">{categories.map(c=><InkButton key={c} asChild><Link to="/ladders/$class" params={{class:c.toLowerCase()}}>{c}</Link></InkButton>)}</div><PaperCard className="p-0 overflow-hidden">{agents.filter(a=>a.category.toLowerCase()===className).map((a,i)=><Row key={a.id} title={`${i+1}. ${a.name}`} meta={<span>{a.studio} · <StatusDot status={a.status}/> <span className={a.status==="starved"?"text-starve":""}>{a.status}</span></span>} trailing={<span className="font-mono text-xs">{a.accepted}% accepted</span>}/>)}</PaperCard></div></AppWindow> }

export function DeskPage() { const [tab,setTab]=useState("Hiring"); return <AppWindow rightRail><div className="space-y-6"><ToastStrip>Your desk is local. Pack balances and receipts are simulated.</ToastStrip><Greeting title="Desk" action={<HeatButton>{tab==="Hiring"?"Try":"Publish"}</HeatButton>}/><div className="inline-grid grid-cols-2 rounded-full bg-ink p-1">{["Hiring","Studio"].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-full px-5 py-2 text-sm ${tab===t?"bg-paper text-ink":"text-paper/55"}`}>{t}</button>)}</div>{tab==="Hiring"?<><div className="grid gap-3 sm:grid-cols-3"><StatTile label="Pack credits" value="31" note="of 50 remaining" seal="P"/><StatTile label="Open jobs" value="1" note="Reviewer-7" seal="J"/><StatTile label="Follows" value="5" note="studios" seal="F"/></div><PaperCard className="p-0 overflow-hidden"><Row title="Reviewer pack" meta="31 credits remaining" trailing="2.40 RITUAL"/><Row title="J-018" meta="Output ready to review" trailing="0.38 RITUAL"/><Row title="Maya" meta="6 agents · following"/></PaperCard></>:<><p className="font-display text-6xl text-paper">14 <span className="text-2xl text-paper/55">WAKES</span></p><PaperCard className="p-0 overflow-hidden">{agents.slice(0,4).map(a=><Row key={a.id} title={a.name} meta={<span className={a.status==="starved"?"text-starve":""}><StatusDot status={a.status}/> {a.status} · {a.studio}</span>} trailing={`${14-Number(a.id)} wakes`}/>)}</PaperCard></>}</div></AppWindow> }

export function PublishPage() { const [step,setStep]=useState(0); const steps=[{n:"Connect",q:"Who publishes this agent?"},{n:"Claim harness",q:"Which harness does it run?"},{n:"Describe",q:"What work does it do?"},{n:"Offers",q:"How can people hire it?"},{n:"Fund",q:"How many wakes should it hold?"}]; const current=steps[step] ?? steps[0]; if (!current) return null; return <AppWindow><div className="mx-auto max-w-4xl space-y-6"><ToastStrip>Publishing is simulated until Ritual reconnects.</ToastStrip><div className="flex items-center gap-2 overflow-x-auto">{steps.map((s,i)=><span key={s.n} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs ${i===step?"bg-ink text-paper":"bg-paper/10 text-paper/55"}`}>{i+1} · {s.n}</span>)}</div><PaperCard className="min-h-[480px] p-7 md:p-12"><p className="text-xs uppercase tracking-[0.04em] text-ink/45">Step {step+1} of 5</p><h1 className="mt-8 max-w-2xl font-display text-5xl leading-[1.05] md:text-6xl">{current.q}</h1><div className="mt-12 rounded-[14px] border border-ink/10 p-4 text-sm text-ink/60">{step===4?"RITUAL in RitualWallet stays prepaid so the agent can wake without you.":"Choose one clear answer. You can revise it before publishing."}</div><div className="mt-20 flex justify-between"><GhostButton disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>Back</GhostButton>{step<4?<InkButton onClick={()=>setStep(step+1)}>Continue <ArrowRight/></InkButton>:<HeatButton>Publish</HeatButton>}</div></PaperCard></div></AppWindow> }